@hostname = libseat.njfu.edu.cn
@port = 443
@host = {{hostname}}:{{port}}
@contentType = application/json
@cookie = f003e2b3-bfa4-4f38-a0fb-0c53093ccedc

### credit
GET https://libseat.njfu.edu.cn/ic-web/creditPunishRec/surPlus
Cookie: ic-cookie={{cookie}}

### 预约记录
GET https://libseat.njfu.edu.cn/ic-web/reserve/resvInfo?beginDate=2023-09-10&endDate=2023-09-14
Cookie: ic-cookie={{cookie}}

### resvId查询account
GET https://libseat.njfu.edu.cn/ic-web/reserve/getSignRec?resvId=143967878
Cookie: ic-cookie={{cookie}}

### 删除
POST https://libseat.njfu.edu.cn/ic-web/reserve/delete
content-type: {{contentType}}
Cookie: ic-cookie={{cookie}}

{
    "uuid": "79929fe68d364f5db8b537a765d80e28"
}

### 每层楼
GET https://libseat.njfu.edu.cn/ic-web/reserve?roomIds=100455344&resvDates=20230923&sysKind=8
Cookie: ic-cookie={{cookie}}

### 预约
POST https://libseat.njfu.edu.cn/ic-web/reserve
cookie: ic-cookie={{cookie}}
content-type: {{contentType}}
content-length: 0

{
    "sysKind": 8,
    "appAccNo": 116718634,
    "resvMember": [
        116718634
    ],
    "resvBeginTime": "2023-09-17 7:30:00",
    "resvEndTime": "2023-09-17 22:00:00",
    "resvDev": [
        100455621
    ]
}

###
GET http://libseat.njfu.edu.cn/scancode.html#/login?sta=1&sysid=1cv&lab=100455331&type=1&dev=100455513&unionid=o8qflt_pthjqtpicujcsyhqm6fj4

### phone login
POST https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/login
content-type: {{contentType}}

{
    "devSn":"100455433",
    "unionId":"o8QfLt_PTHjQtPIcUjcSYhQM6FJ4",
    "type":"1",
    "bind":0
}

### leave
POST https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/templeave
content-type: {{contentType}}

{
    "resvId": 143998984,
}

### back
POST https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/comeback
content-type: {{contentType}}

{
    "resvId": 143998984,
}

### quit
POST https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/quit
content-type: {{contentType}}

{
    "resvId": 143998984,
}

###
GET https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/duration
content-type: {{contentType}}

###
POST https://libseat.njfu.edu.cn/ic-web/phoneSeatReserve/reserve
content-type: {{contentType}}

{
    "duration":376
}

###
GET https://libseat.njfu.edu.cn/ic-web/resvdesk/log?logstring=resvid:143950297,resvname:%e8%92%8b%e9%9b%a8%e5%b3%b0,resvbegintime:1694561400000,resvendtime:1694613600000,resvruleid:1,resvstatus:1093

### 登录

POST https://libic.njfu.edu.cn/ClientWeb/pro/ajax/login.aspx
content-type: application/x-www-form-urlencoded

&id=200855110
&pwd=njfu10003x!
&act=login
