# https://libic.njfu.edu.cn
# ip: 121.248.150.233

@2F-A= 100455344
@2F-B= 100455346
@3F-A= 100455350
@3F-B= 100455352
@3F-C= 100455354
@3FA-=111488386
@4F-A= 100455356
@4FA-=111488388
@5F-A=100455358
@6F-A= 100455360
@7F-A= 106658017
@room_id = {{4F-A}}
@dev_id = 100504097
### 查询图书馆
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/device.aspx
?room_id={{room_id}}
&date={{$datetime 'YYYY-MM-DD' 8 h}}
&act=get_rsv_sta

### 查询座位
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/device.aspx
?dev_id={{dev_id}}
&date={{$datetime 'YYYY-MM-DD' 8 h}}
&act=get_rsv_sta

### 查询研讨间
POST https://libic.njfu.edu.cn/ClientWeb/pro/ajax/device.aspx?
?classkind=1
&kind_id=100501645
&date={{$datetime 'YYYY-MM-DD' 8 h}}
&act=get_rsv_sta

### 查询学号
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/data/searchAccount.aspx
?term=200855110

### 登录
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/login.aspx
content-type: application/x-www-form-urlencoded

&id=200855110
&pwd=njfu10003x!
&act=login

### 个人中心
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/center.aspx
?act=get_History_resv
&strat=90
&StatFlag=New

### 取消预约
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?act=del_resv
&id=142116135

### 预约
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?dev_id={{dev_id}}
&start=2023-05-07 20:00
&end=2023-05-07 22:00
&act=set_resv

### 研讨室预约
POST https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?dev_id={{dev_id}}
&min_user=0
&max_user=8
&mb_list=$111507107,116718634,116718858,116718860
&start=2023-05-09 07:30
&end=2023-05-09 09:30
&act=set_resv

### 登录指定座位
https://libic.njfu.edu.cn/Pages/WxSeatSign.aspx
?lab=100455336
&dev={{dev_id}}
&msn=o8QfLt_PTHjQtPIcUjcSYhQM6FJ4

### 签到座位
# depend on 登陆指定座位
https://libic.njfu.edu.cn/Pages/WxSeatSign.aspx
content-type: application/x-www-form-urlencoded

&DoUserIn=true
&dwUseMin=300

### 签退
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?act=resv_leave
&type=2
&resv_id=142008395

### 举报
https://libic.njfu.edu.cn/Pages/WxReport.aspx
