# https://libic.njfu.edu.cn
# ip: 121.248.150.233

@2F-A= 100455344
@2F-B= 100455346
@3F-A= 100455350
@3F-B= 100455352
@3F-C= 100455354
@3FA-=111488386
@4F-A= 100455356
@4FA-=111488388
@5F-A=100455358
@6F-A= 100455360
@7F-A= 106658017
@room_id = {{4F-A}}
@dev_id = 100500272
### 查询图书馆
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/device.aspx
User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
content-type: application/x-www-form-urlencoded

&byType=devcls
&classkind=8
&room_id={{room_id}}
&date={{$datetime 'YYYY-MM-DD' 8 h}}
&act=get_rsv_sta

### 查询座位
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/device.aspx
User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
content-type: application/x-www-form-urlencoded

&dev_id={{dev_id}}
&date={{$datetime 'YYYY-MM-DD' 8 h}}
&act=get_rsv_sta

### 登录
Post https://libic.njfu.edu.cn/ClientWeb/pro/ajax/login.aspx
content-type: application/x-www-form-urlencoded

&id=200855110
&pwd=**********
&act=login

### 个人中心
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/center.aspx
?act=get_History_resv
&strat=90
&StatFlag=New

### 删除预约
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?act=del_resv
&id=141976788

### 预约
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?dev_id={{dev_id}}
&start=2023-04-26 18:00
&end=2023-04-26 22:00
&act=set_resv

### 签退
https://libic.njfu.edu.cn/ClientWeb/pro/ajax/reserve.aspx
?act=resv_leave
&type=2
&resv_id=142008395
